name: render_list

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  render_list:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          version-type: strict
          version-file: .tool-versions
      - name: Render Template
        run: elixir render_list.exs
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Awesome Livebook list
